@startuml StageFlow_Sprint1_MVP
left to right direction
skinparam actorStyle awesome

skinparam usecase {
BackgroundColor #E8F6F3
BorderColor #117864
ArrowColor #117864
}

actor "Étudiant" as E
actor "Entreprise" as Ent
actor "Administrateur " as Admin
actor "Mobile" as Mob


' =========================
' Étudiant
' =========================

usecase "Consulter tableau de bord étudiant" as UC1
usecase "Consulter offres de stage" as UC2
usecase "Voir détails d’un stage" as UC3
usecase "Postuler à un stage" as UC4
usecase "Suivre l’état des candidatures" as UC5
usecase "Ajouter aux favoris" as UC6
usecase "Ajouter un feedback" as UC12

E -- UC1
E -- UC2
E -- UC3
E -- UC4
E -- UC5
E -- UC6
E -- UC12


' =========================
' Entreprise
' =========================

usecase "Consulter tableau de bord entreprise" as UC7
usecase "Gérer les offres de stage (CRUD)" as UC8
usecase "Gérer candidatures reçues(Accepter / Refuser)" as UC9
usecase "Ajouter un feedback" as UC13

Ent -- UC7
Ent -- UC8
Ent -- UC9
Ent -- UC13



' =========================
' Administrateur
' =========================

usecase "Gérer comptes utilisateurs" as UC10
usecase "Consulter statistiques globales" as UC11
usecase "Modérer les feedbacks" as UC14

Admin -- UC10
Admin -- UC11
Admin -- UC14


' =========================
' Mobile
' =========================

usecase "Consommer l'API" as API

Mob -- API


' =========================
' Authentification
' =========================

usecase "S'authentifier" as Auth

UC1 ..> Auth : <<include>>
UC2 ..> Auth : <<include>>
UC3 ..> Auth : <<include>>
UC4 ..> Auth : <<include>>
UC5 ..> Auth : <<include>>
UC6 ..> Auth : <<include>>
UC7 ..> Auth : <<include>>
UC8 ..> Auth : <<include>>
UC9 ..> Auth : <<include>>
UC10 ..> Auth : <<include>>
UC11 ..> Auth : <<include>>
UC12 ..> Auth : <<include>>
UC13 ..> Auth : <<include>>
UC14 ..> Auth : <<include>>

@enduml