@startuml StageFlow_Mobile_Sprint2
left to right direction
skinparam actorStyle awesome

skinparam package {
    BackgroundColor White
    BorderColor #2C3E50
}

skinparam usecase {
    BackgroundColor #E8F6F3
    BorderColor #117864
    ArrowColor #117864
}

actor "Étudiant" as E
actor "Web" as W


package "Sprint 2 – Mobile (StageFlow)" {

    ' ========================
    ' Fonctionnalités Étudiant
    ' ========================
        
    usecase "Ajouter une offre aux favoris" as UC1
    usecase "Consulter profil" as UC2
    usecase "S'authentifier" as Auth

    E -- UC1
    E -- UC2
    E -- Auth


    ' ========================
    ' Infrastructure Web
    ' ========================
    
    usecase "Fournir l'API mobile" as UC3

    W -- UC3


    ' ========================
    ' Relations
    ' ========================

    UC1 ..> Auth : <<include>>
    UC2 ..> Auth : <<include>>

}

@enduml
