@startuml StageFlow_Sprint3
left to right direction
skinparam actorStyle awesome

skinparam package {
    BackgroundColor White
    BorderColor #2C3E50
}

skinparam usecase {
    BackgroundColor #E8F6F3
    BorderColor #117864
    ArrowColor #117864
}

actor "Étudiant" as E
actor "Entreprise" as Ent
actor "Administrateur" as Admin


package "Sprint 3 – Assistant Virtuel & IA" {

    usecase "Générer un message de motivation (IA)" as UC_Motiv
    usecase "Obtenir des offres recommandées (IA)" as UC_Recom
    
    usecase "Gérer les offres via l'IA" as UC_Offres
    usecase "Gérer les candidatures via l'IA" as UC_Cands

    usecase "Gérer les ressources (établissements, filières, secteurs) via l'IA" as UC_Res
    usecase "Générer des rapports statistiques (IA)" as UC_Stats
    
    usecase "S'authentifier" as Auth

    E -- UC_Motiv
    E -- UC_Recom

    Ent -- UC_Offres
    Ent -- UC_Cands

    Admin -- UC_Res
    Admin -- UC_Stats

    UC_Motiv ..> Auth : <<include>>
    UC_Recom ..> Auth : <<include>>
    UC_Offres ..> Auth : <<include>>
    UC_Cands ..> Auth : <<include>>
    UC_Res ..> Auth : <<include>>
    UC_Stats ..> Auth : <<include>>
}

@enduml