@startuml StageFlow_Sprint1
skinparam actorStyle awesome
left to right direction

skinparam package {
    BackgroundColor White
    BorderColor #2C3E50
}

skinparam usecase {
    BackgroundColor #E8F6F3
    BorderColor #117864
    ArrowColor #117864
}

actor "Étudiant" as E
actor "Entreprise / Admin" as Ent

package "Sprint 1 – MVP (StageFlow)" {

    ' ========================
    ' Espace Étudiant
    ' ========================
    usecase "S'inscrire / Se connecter" as UC1
    usecase "Consulter offres" as UC2
    usecase "Rechercher & Filtrer offres" as UC3
    usecase "Voir détails d’un stage" as UC4
    usecase "Postuler à un stage" as UC5
    usecase "Téléverser CV & Photo Profil" as UC6
    usecase "Suivre l’état des candidatures" as UC7

    E --> UC1
    E --> UC2
    E --> UC3
    E --> UC4
    E --> UC5
    E --> UC7

    UC5 ..> UC6 : <<include>>

    ' ========================
    ' Espace Entreprise
    ' ========================
    usecase "Se connecter (Entreprise / Admin)" as UC8
    usecase "Gérer les offres (CRUD)" as UC9
    usecase "Consulter candidatures reçues" as UC10
    usecase "Gérer candidatures (Accepter / Refuser)" as UC11
    usecase "Consulter tableau de bord" as UC12

    Ent --> UC8
    Ent --> UC9
    Ent --> UC10
    Ent --> UC11
    Ent --> UC12
}

@enduml