@startuml StageFlow_Sprint1_MVP
left to right direction
skinparam actorStyle awesome

skinparam package {
    BackgroundColor White
    BorderColor #2C3E50
}

skinparam usecase {
    BackgroundColor #E8F6F3
    BorderColor #117864
    ArrowColor #117864
}

actor "Étudiant" as E
actor "Entreprise" as Ent
actor "Administrateur Système" as Admin


package "Sprint 1 – MVP (StageFlow)" {

' =========================
' Authentification
' =========================
package "Authentification" #FDEBD0 {
    usecase "S'authentifier" as Auth
}

E -- Auth
Ent -- Auth
Admin -- Auth


' =========================
' Application Web
' =========================
package "Application Web" {

    ' ===== Étudiant =====
    package "Espace Étudiant" {

        usecase "Consulter tableau de bord étudiant" as UC1
        usecase "Consulter offres de stage" as UC2
        usecase "Voir détails d’un stage" as UC3
        usecase "Postuler à un stage" as UC4
        usecase "Téléverser CV & Photo Profil" as UC5
        usecase "Suivre l’état des candidatures" as UC6
        usecase "Ajouter aux favoris" as UC7

    }

    E -- UC1
    E -- UC2
    E -- UC3
    E -- UC4
    E -- UC6
    E -- UC7

    UC4 ..> UC5 : <<include>>


    ' ===== Entreprise =====
    package "Espace Entreprise" {

        usecase "Consulter tableau de bord entreprise" as UC8
        usecase "Gérer les offres de stage (CRUD)" as UC9
        usecase "Consulter candidatures reçues" as UC10
        usecase "Gérer candidatures\n(Accepter / Refuser)" as UC11

    }

    Ent -- UC8
    Ent -- UC9
    Ent -- UC10
    Ent -- UC11

    UC11 ..> UC10 : <<include>>


    ' ===== Administrateur =====
    package "Espace Administrateur" {

        usecase "Gérer comptes utilisateurs" as UC12
        usecase "Modérer les offres publiées" as UC13
        usecase "Consulter statistiques globales" as UC14

    }

    Admin -- UC12
    Admin -- UC13
    Admin -- UC14

}


' =========================
' Application Mobile
' =========================
package "Application Mobile – Étudiant" #E8F8F5 {

    usecase "Consulter tableau de bord étudiant" as M1
    usecase "Consulter les offres de stage" as M2
    usecase "Consulter les candidatures" as M3

    E -- M1
    E -- M2
    E -- M3

}

}
@enduml