@startuml StageFlow_UseCase_Global
left to right direction
skinparam actorStyle awesome

skinparam packageStyle rectangle
skinparam shadowing false

skinparam package {
    BackgroundColor White
    BorderColor #2C3E50
}

skinparam usecase {
    BackgroundColor #E8F6F3
    BorderColor #117864
}

skinparam nodesep 25
skinparam ranksep 25

actor "Étudiant" as E
actor "Entreprise" as Ent
actor "Administrateur" as Admin


package "Authentification" #FDEBD0 {

    usecase "S'inscrire / Se connecter" as Auth

}

E -- Auth
Ent -- Auth
Admin -- Auth


package "Application Web" {

    package "Étudiant" {

        usecase "Tableau de bord" as UC1
        usecase "Consulter offres" as UC2
        usecase "Voir détails stage" as UC3
        usecase "Postuler stage" as UC4
        usecase "Téléverser CV" as UC5
        usecase "Suivre candidatures" as UC6
        usecase "Ajouter favoris" as UC7
        usecase "Ajouter commentaire" as UC8
    }

    E -- UC1
    E -- UC2
    E -- UC3
    E -- UC4
    E -- UC6
    E -- UC7
    E -- UC8

    UC4 ..> UC5 : <<include>>


    package "Entreprise" {

        usecase "Tableau de bord entreprise" as UC9
        usecase "Gérer offres" as UC10
        usecase "Consulter candidatures" as UC11
        usecase "Gérer candidatures" as UC12
        usecase "Ajouter commentaire" as UC13
    }

    Ent -- UC9
    Ent -- UC10
    Ent -- UC11
    Ent -- UC12
    Ent -- UC13

    UC12 ..> UC11 : <<include>>


    package "Administrateur" {

        usecase "Gérer comptes" as UC14
        usecase "Modérer offres" as UC15
        usecase "Modérer commentaires" as UC16
        usecase "Voir statistiques" as UC17
    }

    Admin -- UC14
    Admin -- UC15
    Admin -- UC16
    Admin -- UC17

}


package "Application Mobile" #E8F8F5 {

    usecase "Tableau de bord étudiant" as M1
    usecase "Consulter offres" as M2
    usecase "Consulter candidatures" as M3

    E -- M1
    E -- M2
    E -- M3

}

@enduml