@startuml StageFlow_Cas_Utilisation_Global
skinparam actorStyle awesome
left to right direction

skinparam package {
    BackgroundColor White
    BorderColor #2C3E50
}

skinparam usecase {
    BackgroundColor #E8F6F3
    BorderColor #117864
    ArrowColor #117864
}

actor "Étudiant" as E
actor "Entreprise / admin" as Ent

package "StageFlow - Plateforme de Gestion de Stages" {

    ' ========================
    ' Espace Étudiant
    ' ========================

    usecase "S'inscrire / Se connecter" as UC1
    usecase "Consulter offres" as UC2
    usecase "Rechercher & Filtrer offres" as UC3
    usecase "Voir détails d’un stage" as UC4
    usecase "Postuler à un stage" as UC5
    usecase "Téléverser CV & Photo Profil" as UC6
    usecase "Suivre l’état des candidatures" as UC7
    usecase "Recevoir notifications" as UC8

    E -- UC1
    E -- UC2
    E -- UC3
    E -- UC4
    E -- UC5
    E -- UC7
    E -- UC8

    UC5 ..> UC6 : <<include>>

    ' ========================
    ' Espace Entreprise
    ' ========================

    usecase "Se connecter (Entreprise)" as UC9
    usecase "Gérer les offres (CRUD)" as UC10
    usecase "Consulter candidatures reçues" as UC11
    usecase "Gérer candidatures" as UC12
    usecase "Accepter candidature" as UC13
    usecase "Refuser candidature" as UC14
    usecase "Consulter tableau de bord" as UC15
    usecase "Voir statistiques détaillées" as UC16

    Ent -- UC9
    Ent -- UC10
    Ent -- UC11
    Ent -- UC12
    Ent -- UC15
    Ent -- UC16

    UC12 ..> UC13 : <<include>>
    UC12 ..> UC14 : <<include>>
}
@enduml